/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AttachmentMetadata = IDL.Record({
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
  'filename' : IDL.Text,
});
export const Note = IDL.Record({
  'title' : IDL.Text,
  'verified' : IDL.Bool,
  'subject' : IDL.Text,
  'unit' : IDL.Text,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'lastUpdatedTimestamp' : IDL.Int,
  'createdTimestamp' : IDL.Int,
  'uploader' : IDL.Principal,
  'attachments' : IDL.Vec(AttachmentMetadata),
});
export const NoteId = IDL.Nat;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getNoteById' : IDL.Func([NoteId], [Note], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerifiedNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isModerator' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(AttachmentMetadata)],
      [NoteId],
      [],
    ),
  'verifyNote' : IDL.Func([NoteId, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AttachmentMetadata = IDL.Record({
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const Note = IDL.Record({
    'title' : IDL.Text,
    'verified' : IDL.Bool,
    'subject' : IDL.Text,
    'unit' : IDL.Text,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'lastUpdatedTimestamp' : IDL.Int,
    'createdTimestamp' : IDL.Int,
    'uploader' : IDL.Principal,
    'attachments' : IDL.Vec(AttachmentMetadata),
  });
  const NoteId = IDL.Nat;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMySubmissions' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getNoteById' : IDL.Func([NoteId], [Note], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerifiedNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isModerator' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(AttachmentMetadata)],
        [NoteId],
        [],
      ),
    'verifyNote' : IDL.Func([NoteId, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };