/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttachmentMetadata {
  'fileSize' : bigint,
  'fileType' : string,
  'filename' : string,
}
export interface Note {
  'title' : string,
  'verified' : boolean,
  'subject' : string,
  'unit' : string,
  'rejectionReason' : [] | [string],
  'description' : string,
  'lastUpdatedTimestamp' : bigint,
  'createdTimestamp' : bigint,
  'uploader' : Principal,
  'attachments' : Array<AttachmentMetadata>,
}
export type NoteId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMySubmissions' : ActorMethod<[], Array<Note>>,
  'getNoteById' : ActorMethod<[NoteId], Note>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedNotes' : ActorMethod<[], Array<Note>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isModerator' : ActorMethod<[Principal], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitNote' : ActorMethod<
    [string, string, string, string, Array<AttachmentMetadata>],
    NoteId
  >,
  'verifyNote' : ActorMethod<[NoteId, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];